export const inventoryData = [
  {
    id: 1,
    name: "Carrot",
    category: "Vegetable",
    stock: 12,
    description: "Sample Description",
    image: require("@/assets/images/measf.jpg"),
  },
  {
    id: 2,
    name: "Apple",
    category: "Fruit",
    stock: 2,
    description: "Sample Description",
    image: require("@/assets/images/measf.jpg"),
  },
  {
    id: 3,
    name: "Chicken",
    category: "Protein",
    stock: 6,
    description: "Sample Description",
    image: require("@/assets/images/measf.jpg"),
  },
  {
    id: 4,
    name: "Bagel",
    category: "Grain",
    stock: 8,
    description: "Sample Description",
    image: require("@/assets/images/measf.jpg"),
  },
  {
    id: 5,
    name: "Kiwi",
    category: "Fruit",
    stock: 8,
    description: "Sample Description",
    image: require("@/assets/images/measf.jpg"),
  },
  {
    id: 6,
    name: "Cheese",
    category: "Dairy",
    stock: 4,
    description: "Sample Description",
    image: require("@/assets/images/measf.jpg"),
  },
   {
    id: 7,
    name: "Cherry",
    category: "Fruit",
    stock: 20,
    description: "Sample Description",
    image: require("@/assets/images/measf.jpg"),
  },
];
